Update purisSIF environment

diff --git a/scripts/stools/purisSIF/2datain b/scripts/stools/purisSIF/2datain
--- a/scripts/stools/purisSIF/2datain
+++ b/scripts/stools/purisSIF/2datain
@@ -1,6 +1,35 @@
 #!/bin/bash
 
-rsync -rv --chmod=ugo=rw ${DIRDADOS}/MONAN_datain/datain/fixed ${DATAIN}
-rsync -rv --chmod=ugo=rwx ${DIRDADOS}/MONAN_datain/execs ${DIRHOMED}
-ln -sf ${DIRDADOS}/MONAN_datain/datain/WPS_GEOG ${DATAIN}
+#rsync -rv --chmod=ugo=rw ${DIRDADOS}/MONAN_datain/datain/fixed ${DATAIN}
+#rsync -rv --chmod=ugo=rwx ${DIRDADOS}/MONAN_datain/execs ${DIRHOMED}
+#ln -sf ${DIRDADOS}/MONAN_datain/datain/WPS_GEOG ${DATAIN}
+
+if [ ! -e "${DATAIN}/WPS_GEOG" ]; then
+    if [ ! -f "WPS_GEOG.tar.gz" ]; then
+        if wget "https://dataserver.cptec.inpe.br/dataserver_dimnt/monan/MONAN-Model/monan_datain/WPS_GEOG.tar.gz"; then
+            echo "wget OK!"
+        else
+            echo "wget error!"
+            echo "Link: https://dataserver.cptec.inpe.br/dataserver_dimnt/monan/MONAN-Model/monan_datain/WPS_GEOG.tar.gz"
+            exit 1
+        fi
+    fi
+    mkdir -p "${DATAIN}/WPS_GEOG"
+    tar -xzvf WPS_GEOG.tar.gz -C "${DATAIN}/"
+    rm WPS_GEOG.tar.gz
+fi
+if [ ! -e "${DATAIN}/fixed" ]; then
+    if [ ! -f "fixed.tar.gz" ]; then
+        if wget "https://dataserver.cptec.inpe.br/dataserver_dimnt/monan/MONAN-Model/monan_datain/fixed.tar.gz"; then
+            echo "wget OK!"
+        else
+            echo "wget error"
+            echo "Link: https://dataserver.cptec.inpe.br/dataserver_dimnt/monan/MONAN-Model/monan_datain/fixed.tar.gz"
+            exit 1
+        fi
+    fi
+    mkdir -p "${DATAIN}/fixed"
+    tar -xzvf fixed.tar.gz -C "${DATAIN}/"
+    rm fixed.tar.gz
+fi
 
